### ISSUE TITLE
classCastException - onActivity destroyed

### ISSUE THREAD

**Issue by RasmusKOlsen** [skimarxall/RxFlux#17]
Hi,

I am getting a ClassCastException due to onDestory in RxFlux not checking instanceof before casting (line 112).
It seems there is already a pull request that fixes this issue(https://github.com/skimarxall/RxFlux/pull/12), and it appears to be merged - however it is not part of the 0.3.2 release.

**Comment by marcelpinto** [comment]
Yes I'll try to merge it with the rest and make a release ASAP.

**Comment by marcelpinto** [comment]
done
